# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.4.5.dev8+g14773d1.d20220712'
__version_tuple__ = version_tuple = (0, 4, 5, 'dev8', 'g14773d1.d20220712')
