#
# Paths to validation tools
# See README for more details
#

#HEPMC2LOCATION   = ../../HepMC209
HEPMC3LOCATION   = ../builds
HEPMC3INTERFACES = ../interfaces

ROOTCONFIG = root-config

#PHOTOSLOCATION_HEPMC2 = ../../Photospp.3.54-HepMC2/
#PHOTOSLOCATION_HEPMC3 = ../../Photospp.3.54/

#TAUOLALOCATION_HEPMC2 = ../../Tauola.1.1.4-HepMC2/
#TAUOLALOCATION_HEPMC3 = ../../Tauola.1.1.4/

#PYTHIA8LOCATION_HEPMC2 = ../../pythia8185/
#PYTHIA8LOCATION_HEPMC3 = ../../pythia8185/

#MCTESTERLOCATION_HEPMC2 = ../../mc-tester-1.25.0/
#MCTESTERLOCATION_HEPMC3 = ../../mc-tester-1.25.0/
