name: doc

on:
  pull_request:
  push:
    branches: [main]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 3
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - run: python -m pip install -v -e .[doc]
    - run: python docs/build.py
    - uses: peaceiris/actions-gh-pages@v3
      if: github.ref_type == 'tag' || github.ref_name == 'main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
